- handheld/gameboy/shader-files/gb-pass0.slang
- handheld/gameboy/shader-files/gb-pass1.slang
- handheld/gameboy/shader-files/gb-pass3.slang
works a little bit better.
If the blending_mode macro on gb-pass1 is set to 0, we'll get only the
green background color.
> (gameboy) A couple of MAD optimizations, some formatting and ensure the shader

- xbr/shaders/super-xbr/super-xbr-pass1.slang
- xbr/super-xbr-2p.slangp
introduces unintended motion blur.
Move the slang preset to the correct location.
> (super-xbr) Use 'Original' instead of 'OriginalHistory1'. The latter

- motionblur/braid-rewind.slangp
- motionblur/feedback.slangp
- motionblur/motionblur-blue.slangp
- motionblur/motionblur-color.slangp
- motionblur/motionblur-simple.slangp
- motionblur/shaders/braid-rewind.slang
- motionblur/shaders/feedback.slang
- motionblur/shaders/motionblur-blue.slang
- motionblur/shaders/motionblur-color.slang
- motionblur/shaders/motionblur-simple.slang
The braid-rewind shader won't compile because it relies on
'global.FrameDirection', meant to be the counterpart to Cg's
IN.frame_direction.
> (motionblur) Everything ported to slang.

- xsal/2xsal-level2 - CRT.slangp
- xsal/2xsal-level2.slangp
- xsal/2xsal.slangp
- xsal/4xsal-level2 - CRT.slangp
- xsal/4xsal-level2 - DDT.slangp
- xsal/4xsal-level2.slangp
- xsal/shaders/2xsal-level2.slang
- xsal/shaders/2xsal.slang
Had to remove what seems to be the AMD rounding fix off of the vertex shaders in order to better match the Cg versions.
The only optimizations done were using the precalculated Z and W coordinates from SourceSize, instead of X and Y (turns a couple of divisions into multiplications).
> (xSaL) Translated all files from Cg to slang

- misc/yiq-hue-adjustment.slang
Ported from https://github.com/AnalyticalGraphicsInc/cesium/blob/master/Source/Shaders/Builtin/Functions/hue.glsl
The shader allows hue adjustments in degrees from -360° to 360°, which is converted to radians for the shader. It makes use of colorspace-tools.h for the RGB->YIQ->RGB conversion.
> Add a YIQ Hue adjustment shader

- misc/nes-color-decoder-alt.slang
- misc/nes-color-decoder-sony.slang
- misc/nes-color-decoder.slang
- ntsc/ntsc-nes.slangp
- presets/nes-color-decoder+pixellate.slangp
Ported from https://forums.nesdev.com/viewtopic.php?p=85060#p85060
The shader utilizes the 'raw' color palette in Nestopia and FCEUmm cores, it will produce garbage colors otherwise.
The default shader uses the FCC sanctioned YIQ to RGB conversion matrix, the other two varieties use alternative conversion matrices.
I included presets with Pixellate and NTSC-256px shader combinations as well.
> Add a NTSC NES color decoder shader, based on Bisqwit's code

- misc/nes-color-decoder-alt.slang
- misc/nes-color-decoder-sony.slang
- misc/nes-color-decoder.slang
Fixes a glitch that occurred when Castlevania III password screen fades to black.
> (nes-color-decoder) Use correct level when color is 0xE and 0xF

- xbrz/shaders/xbrz-freescale.slang
- xbrz/xbrz-freescale.slangp
this uses the same detection code as the other xbrz shaders, with the difference that it can work at any output scale (even non-integer).
performance requirements are also lower since it can directly determine the output pixel value, instead of computing all the values in the region and then selecting the correct one.
> add xbrz-freescale.

- handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color-4k.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color.slang
This pull request just updates the simpletex_lcd+gba-color shaders with the new colour correction values from version 9.2 of Pokefan531's gba-color shader ([src](https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/159)).
> [handheld] simpletex_lcd: Update GBA colour correction

- handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color-4k.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color.slang
This pull request just updates the simpletex_lcd+gbc-color shaders with the new colour correction values from version 10.0 of Pokefan531's gbc-color shader ([src](https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/160))
> [handheld] simpletex_lcd: Update GBC colour correction 

- motionblur/mix_frames.slangp
- motionblur/mix_frames_smart.slangp
- motionblur/shaders/mix_frames.slang
- motionblur/shaders/mix_frames_smart.slang
This PR just adds slang versions of the frame mixing shaders described in [glsl-shaders PR#82](https://github.com/libretro/glsl-shaders/pull/82).
> Add frame mixing shaders

- motionblur/braid-rewind.slangp
- motionblur/shaders/braid-rewind.slang
Fixed syntax of the profile and shader, also the true type of FrameDirection is `int` (if that actually matters).
> Readd braid-rewind with syntax fix

- bilinear.slangp
- nearest.slangp
Adds bilinear.slangp and nearest.slangp to make it slightly more intuitive to load stock shaders.
Stock shaders are useful as a sort of "shader blacklist" for content if saved as a global/core/folder/game preset.
Sort of related and motivated by https://github.com/libretro/RetroArch/pull/9315 and https://github.com/libretro/RetroArch/pull/9320
> add stock presets

- misc/img_mod.slang
The rgb_grain function wasn't added to be applied, so I added the line for it and uncommented it.
> Missing rgb_grain selection?

- handheld/lcd1x.slangp
- handheld/lcd1x_nds.slangp
- handheld/lcd1x_psp.slangp
- handheld/shaders/lcd1x.slang
- handheld/shaders/lcd1x_nds.slang
- handheld/shaders/lcd1x_psp.slang
This PR adds a very simple/trivial `lcd1x` handheld shader that is almost identical to `lcd3x` but:
- Omits the colour separation effect (this always gives me eye-strain...)
- Has scanlines that properly align with pixel columns/rows
Here are a couple of example screenshots:
The nice thing about this shader is that it handles low display resolutions quite well, producing even scanlines regardless of scaling. It also has minimal performance impact.
One interesting use case is applying it to PSX content on a phone with a 720p display:
This 'feels' very much like running PSX games on an idealised PSP.
In addition to the base `lcd1x` shader, two device-specific variants are included:
- `lcd1x_nds`: This applies NDS colour correction, and can be used with arbitrary internal scale factors: …
> Add lcd1x shaders

- dithering/shaders/mdapt/passes/mdapt-pass0.slang
Add prefix to MDAPT shader parameters to avoid parameter name conflicts.
> Add prefix to MDAPT shader parameters

- handheld/console-border/gb-pocket-2x.slangp
- handheld/console-border/gb-pocket-3x.slangp
- handheld/console-border/gb-pocket-4x.slangp
- handheld/console-border/gb-pocket-5x.slangp
- handheld/console-border/gb-pocket-6x.slangp
- handheld/console-border/shader-files/gb-pass0.slang
- handheld/console-border/shader-files/gb-pass1.slang
This fixes the round dots present on the Game Boy border shaders affecting specially the GB Pocket shaders, which I believe were not at all accurate to the geometry of the pixels on a real GB Pocket screen.
The original DMG presets, at their default "Neighbor Blending" parameter values, don't exhibit this problem as much, and as such this change practically doesn't affect their picture at all. This primarily affects the GB Pocket presets only.
This was caused by the fact that the blending shader doesn't blend the intersection of the horizontal and vertical gaps, causing that spot to be much brighter than the rest of the gap.
This pull request changes the way the adjacent texel blending works, by also taking into consideration the intersection texels.
The process is more complex than …
> Fixed round dots on Gameboy shaders

- handheld/shaders/lcd-cgwg/lcd-grid-v2.slang
For whatever reason, having "param" instead of "params" was preventing it from running. Fixing this allows lcd-grid-v2 and the many multipass shaders using it to run on the Metal build.
> Fix lcd-grid-v2 on macOS Metal

- handheld/shaders/color/gba-color.slang
- handheld/shaders/color/gbc-color.slang
- handheld/shaders/color/nds-color.slang
- handheld/shaders/lcd1x_nds.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color-4k.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color-4k.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd_720p+gba-color.slang
- handheld/shaders/simpletex_lcd/simpletex_lcd_720p+gbc-color.slang
- presets/retro-v2+gba-color.slangp
- presets/retro-v2+gbc-color.slangp
This PR updates Pokefan531's GBA/GBC/NDS colour correction shaders to the latest version: https://forums.libretro.com/t/real-gba-and-ds-phat-colors/1540/190
It also updates all derived shaders/presets (i.e. the colour-correction versions of lcd1x, simpletex_lcd, etc.)
> Update GBA/GBC/NDS colour correction parameters

- xbr/shaders/xbr-lv2-3d.slang
I don't know really know how this shaders works but this change allows a value to be set to reduce the ringing artifact around 3D objects. Please let me know if there's a better way to make this shader behave better ...
> Add 'Reduce Artifact' option to xbr-lv2-3d.slang

- crt/crt-blurPi-sharp.slangp
- crt/crt-blurPi-soft.slangp
- crt/shaders/crt-blurPi.slang
I've created a low overhead shader for low res screens (640 x 480 or less), mostly targeted towards raspberry pi 4.
The unique thing about it is that it provides customizable scanlines that are rendered independently from the game resolution, as well as configurable softness / blur. This is very useful when your screen has few pixels, as in most other shaders with scanlines they always seem to stand out. It comes with two variants, one based on the nearest neighbor interpolation, and one based on the linear interoplation.
Those don't look that great here (on a retina screen) but they do look fine on a 640 x 480 LCD on a rpi4.
crt-blurPi-soft.slangp
crt-blurPi-sharp.slangp
> add crt-blurPi slang shader variants

- ntsc/shaders/ntsc-adaptive-tate/ntsc-tate-pass2.slang
- ntsc/shaders/ntsc-adaptive/ntsc-pass2.slang
Makes the 2_phase/above 300pixels wide part of the code run a lot faster on Adreno.
Tested on a snapdragon 870: it was crawling at a point where navigating RA menus was difficult before when applied, now it's running full speed and can FF in Sonic over 150fps.
> ntsc-adaptive adreno optimisation

- crt/shaders/zfast_crt.slang
Follow-up of https://github.com/libretro/RetroArch/pull/12816
> fix zfast_crt for rotated games

- scanlines/shaders/integer-scaling-scanlines.slang
- scanlines/shaders/integer-scaling-scanlines.slangp
This adds an integer scaling mode pixel perfect scanline shader for use with low resolution monitors, underpowered machines, the new HDR mode in RetroArch and for people who want pixel sharp scanlines with absolutely no moire patterns (but with the downside that integer scaling must be on and so not fill up the screen or over fill the screen)
> Add integer scaling mode pixel perfect scanline shader

- anti-aliasing/shaders/smaa/SMAA.hlsl
SMAA: Fix color edge detection
Fix incorrect calculation of local contrast adaption in color edge detection
This is the fix from PR iryoku/smaa#11
I decided to port this fix as I was able in my tests to gather image evidence showing top/left edges that were obviously being missed by Color Edge Detection, that are fixed by the changes in this commit. Although the problem affects a lot of edges, it is rarely so obvious like in this image.
> SMAA: Fix color edge detection

- handheld/console-border/gba-agb001-color-motionblur-1x.slangp
- handheld/console-border/gba-agb001-color-motionblur-2x.slangp
- handheld/console-border/gba-agb001-color-motionblur-3x.slangp
- handheld/console-border/gba-ags001-color-motionblur-1x.slangp
- handheld/console-border/gba-ags001-color-motionblur-2x.slangp
- handheld/console-border/gba-ags001-color-motionblur-3x.slangp
The AGB and AGS screen shaders always output 4x the base res (160p), so
1x is 640p, 2x is 1280p and 3x is 1920p.
> Add border presets for GBA with AGB-001 and AGS-001 screen shaders

- presets/crt-geom-deluxe-ntsc-adaptive.slangp
There's no NTSC preset for the crt-geom-deluxe shader (there's only presets for the older crt-geom one.) So I made one.
> Add NTSC preset for crt-geom-deluxe

- crt/shaders/geom-deluxe/geom-deluxe-params.inc
The current step value for the overscan parameters is 0.02, which is way too coarse. 0.005 is more useful. The scanline weight step value is 0.05, which is also a bit coarse, which I changed to 0.01.
> crt-geom-deluxe: finer grained overscan and scanline weight parameters

- crt/crt-sony-pvm-4k-hdr.slangp
- crt/shaders/crt-sony-pvm-4k-hdr.slang
v1.0 of Sony PVM 4K HDR shader that tries to emulate a Sony PVM 20L4 CRT. Again requires a HDR capable screen typically of at least 700 nits (but may need less for OLEDs) This version adds support for different resolution patterns see shader for more details
> v1.0 of Sony PVM 4K HDR shader that tries to emulate a Sony PVM 20L4

- crt/shaders/zfast_crt/zfast_crt_coarsemask.slang
- crt/shaders/zfast_crt/zfast_crt_finemask.slang
- crt/shaders/zfast_crt/zfast_crt_impl.inc
- crt/zfast-crt-hdmask.slangp
- crt/zfast-crt.slangp
To avoid duplicating the whole shader implementation, the needed define
has been split into its own file, and the shader implementation is now
in an include file.
> zfast-crt: add preset for the coarse mask, suitable for HD displays

- crt/shaders/geom-deluxe/crt-geom-deluxe.slang
Bring interlacing factor claculation back in line with crt geom, fixes #217.
> Display 480p content at full res with interlacing off

- presets/crt-royale-ntsc-composite.slangp
- presets/crt-royale-ntsc-svideo.slangp
The Royale NTSC presets were not using relative multipliers. This fixes that.
> Use relative multiplier on NTSC Royale presets

- hdr/crt-sony-pvm-4k-hdr.slangp
- hdr/shaders/crt-hdr.slang
- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/scanline_generation.h
Fixed gamma curve - was using sRGB now using rec.601 / rec.709 gamma curve 
Added NTSC-U, NTSC-J, PAL colour systems and corresponding default white points 
Added colour grading: white temperature, brightness, contrast
Moved scanline_size out to main shader for easier integration with HSM
> V5.0 Sony PVM 4K HDR Shader

- hdr/crt-sony-megatron-bang-olufsen-mx8000-hdr.slangp
- hdr/crt-sony-megatron-bang-olufsen-mx8000-sdr.slangp
- hdr/crt-sony-megatron-jvc-d-series-AV-36D501-hdr.slangp
- hdr/crt-sony-megatron-jvc-d-series-AV-36D501-sdr.slangp
- hdr/crt-sony-megatron-jvc-professional-TM-H1950CG-hdr.slangp
- hdr/crt-sony-megatron-jvc-professional-TM-H1950CG-sdr.slangp
- hdr/crt-sony-megatron-sammy-atomiswave-hdr.slangp
- hdr/crt-sony-megatron-sammy-atomiswave-sdr.slangp
- hdr/crt-sony-megatron-sega-virtua-fighter-hdr.slangp
- hdr/crt-sony-megatron-sega-virtua-fighter-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-1910-hdr.slangp
- hdr/crt-sony-megatron-sony-pvm-1910-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-20L4-hdr.slangp
- hdr/crt-sony-megatron-sony-pvm-20L4-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-2730-hdr.slangp
- hdr/crt-sony-megatron-sony-pvm-2730-sdr.slangp
- hdr/crt-sony-megatron-toshiba-microfilter-hdr.slangp
- hdr/crt-sony-megatron-toshiba-microfilter-sdr.slangp
- hdr/crt-sony-megatron-viewsonic-A90f+-hdr.slangp
- hdr/crt-sony-megatron-viewsonic-A90f+-sdr.slangp
- hdr/crt-sony-megatron.slangp
- hdr/shaders/crt-sony-megatron-hdr-pass.slang
- hdr/shaders/crt-sony-megatron.slang
- hdr/shaders/include/parameters.h
Fixed all the presets as I hadn't included crt-sont-megatron.slangp - oops! 
Added SDR versions of all the shader presets for ease of use 
Renamed original presets with hdr postfix 
Inverted HDR shader value so SDR is on 0 and HDR is on 1
> V2.6 Sony Megatron Shader

- hdr/crt-sony-megatron-bang-olufsen-mx8000-sdr.slangp
- hdr/crt-sony-megatron-jvc-d-series-AV-36D501-sdr.slangp
- hdr/crt-sony-megatron-jvc-professional-TM-H1950CG-sdr.slangp
- hdr/crt-sony-megatron-sammy-atomiswave-sdr.slangp
- hdr/crt-sony-megatron-sega-virtua-fighter-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-1910-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-20L4-sdr.slangp
- hdr/crt-sony-megatron-sony-pvm-2730-sdr.slangp
- hdr/crt-sony-megatron-toshiba-microfilter-sdr.slangp
- hdr/crt-sony-megatron-viewsonic-A90f+-sdr.slangp
- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/gamma_correct.h
- hdr/shaders/include/parameters.h
Fixed colour issues when skipping phosphor gamuts 
Fixed gamma curves cropping dark colours (as per spec but not wanted early on in colour correction) 
Fixed up SDR presets to have zero values for main colour controls apart from gamma which is moved up to try and compensate for the dimmness
> V3.1 Sony Megatron Shader

- ddt/cut.slangp
- ddt/ddt-extended.slangp
- ddt/ddt-sharp.slangp
- ddt/shaders/cut.slang
- ddt/shaders/ddt-extended.slang
- ddt/shaders/ddt-sharp.slang
- ddt/shaders/ddt-waterpaint.slang
- ddt/shaders/ddt.slang
- Add a port of CUT shaders. A kind of DDT filter with some useful params to control interpolation;
- Fix DDT shaders (broken when porting from Cg to Slang). Courtesy of guest.r.
> Add CUT and fix DDT shaders

- reshade/magicbloom.slangp
Capitalization mismatch on one of the texture files, seems like it might fail on Linux or Android even though it's fine on windows
> Fixed Magic Bloom capitalization error

- xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass0.slang
- xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass1.slang
- xbr/xbr-lv2-small-details.slangp
- Avoid filtering (and detroying) dithering. Improves IQ on games that uses it (genesis mainly).
> Add xbr-lv2-small-details shaders

- cubic/shaders/spline16-x.slang
- cubic/shaders/spline16-y.slang
- cubic/shaders/spline36-x.slang
- cubic/shaders/spline36-y.slang
- cubic/spline16-fast.slangp
- cubic/spline36-fast.slangp
- windowed/lanczos3-fast.slangp
- windowed/shaders/lanczos3-x.slang
- windowed/shaders/lanczos3-y.slang
Three general purpose multipass (orthogonally separated) shaders:
- lanczos3-fast: lanczos with 3-taps;
- spline16-fast: looks like lanczos2 with slightly less ringing;
- spline36-fast: looks like lanczos3 with  slightly less ringing.
> Add lanczos, spline16 and spline36

- hdr/crt-sony-megatron-sammy-atomiswave-hdr.slangp
- hdr/crt-sony-megatron-sammy-atomiswave-sdr.slangp
- hdr/shaders/crt-sony-megatron.slang
- hdr/shaders/include/parameters.h
Fixed 800TVL BGR aperture grille mask 
Recalibrated the sammy atomiswave preset that now takes advantage of the high precision gamma 
Reorganised the gamma parameters to be a bit more intuitive than gamma in/out - doesn't effect presets
> V3.6 Sony Megatron Shader

- hdr/shaders/include/gamma_correct.h
Fixed DCI-P3 transform error - we now have a correct DCI-P3 space
> V3.7 Sony Megatron Shader

- hdr/shaders/crt-sony-megatron-hdr-pass.slang
- hdr/shaders/crt-sony-megatron-source-pass.slang
- hdr/shaders/crt-sony-megatron.slang
- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/gamma_correct.h
- hdr/shaders/include/hdr10.h
Fixed primary transforms for wide colour gamut systems such as HDR breaking the mask and resulting in muddy colours.  Hopefully fixes issues for a number of people and possibly those with OLED screens.
> V4.0 Sony Megatron Shader

- hdr/shaders/crt-sony-megatron-hdr-pass.slang
- hdr/shaders/crt-sony-megatron-source-pass.slang
- hdr/shaders/crt-sony-megatron.slang
- hdr/shaders/include/parameters.h
Added mask accurate/colour accurate switch which effects HDR and DCI-P3 to parameters so that users can choose whether they want 100% pitch black mask or more correct looking colours i.e. not so yellow-y looking greens. Defaults to latter which is the original behaviour.
> V4.1 Sony Megatron Shader

- hdr/crt-sony-megatron-default-hdr.slangp
- hdr/crt-sony-megatron-gba-gbi-hdr.slangp
Added two new presets - one is what I regard a good default for HDR the other is for an emulation of GBA and the GBI on a CRT.
>  V4.1 Sony Megatron Shader - Presets

- hdr/crt-sony-megatron-default-hdr.slangp
- hdr/crt-sony-megatron-gba-gbi-hdr.slangp
Made colour accurate the default setting for the 'default' and 'gba-gbi' presets
> V4.1 Sony Megatron Shader - Presets

- hdr/shaders/crt-sony-megatron.slang
Fixed up slot masks that were broken during my last large refactor
Made the 4K slot masks slightly taller which now makes them different to the slightly shorter 1080p slot masks.  Users can now switch between these sizes if they wish by selecting the 1080p or 4K and dropping down/up a TVL setting. Slightly confusing I know but kind of makes sense.
> V4.3 Sony Megatron Shader

- dithering/sgenpt-mix-multipass.slangp
- dithering/shaders/sgenpt-mix/linearize.slang
- dithering/shaders/sgenpt-mix/sgenpt-mix-pass1.slang
- dithering/shaders/sgenpt-mix/sgenpt-mix-pass2.slang
- dithering/shaders/sgenpt-mix/sgenpt-mix-pass3.slang
- dithering/shaders/sgenpt-mix/sgenpt-mix-pass4.slang
- dithering/shaders/sgenpt-mix/sgenpt-mix-pass5.slang
- Checkerboard treatment on par with checkerboar-dedither shaders (it’ll indeed be incorporated eventually);
- Vertical Lines dedither improved, less false positives (though a bit of false negative);
- CB and VL independent options.
> Add sgenpt-mix-multipass shaders

- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/gamma_correct.h
Removed gamma guards as they were corrupting the image as you went to the extremes of gamma - this is not what the various standard's do.  I will revisit this once I figure out why they are needed and why they are corrupting the image for now they are out.
> V4.4 Sony Megatron Shader

- hdr/shaders/crt-sony-megatron.slang
Bring ReShade and RetroArch versions more inline with each other
Attempt to fix performance on android devices of shadow and slot masks
> V4.5 Sony Megatron Shader

- handheld/console-border/gba-lcd-grid-v2.slangp
- handheld/console-border/gba.slangp
- handheld/console-border/gbc-lcd-grid-v2.slangp
- handheld/console-border/gbc.slangp
- handheld/console-border/gg.slangp
- handheld/console-border/ngpc.slangp
- handheld/console-border/psp.slangp
- handheld/console-border/shader-files/lcd-cgwg/lcd-grid-v2.slang
- handheld/console-border/shader-files/lcd-cgwg/lcd-grid.slang
This comes as a follow-up of the previous handheld-border [cleanup](https://github.com/libretro/slang-shaders/pull/249).
With those changes, some shaders had to be scaled in the shaders pass menu, which could confuse the users, as it's not possible to indicate which pass is the correct one to scale.
With this change, LCD-grid based shaders can now scale by a simple parameter, in the same way the DMG shaders do.
This is particularly useful for non-square pixel consoles such as the GameGear, as this change also introduces a "Pixel Aspect Ratio" parameter.
For this I had to change the `lcd-grid.slang` and `lcd-grid-v2.slang` shaders slightly, but I decided to keep the originals as they are and create a specialized copy on the handheld-border shaders folder. To see what changed you can do a …
> Allow LCD-grid handheld-border shaders to scale by parameter

- handheld/console-border/shader-files/lcd-cgwg/lcd-grid-v2.slang
- handheld/console-border/shader-files/lcd-cgwg/lcd-grid.slang
The new changes to allow LCD-based shaders to be scaled by a parameter introduced a problem where the processing was being applied to the whole viewport instead of just the game area.
This caused blurriness at the cutoff point and lowered performance.
This fixes it and increases performance.
I don't know why the diff looks huge (probably because I changed the indentation), but in reality the only thing changed was an added if-else block to the whole fragment stage.
This is the added condition:
`if(abs(vTexCoord.x - 0.5) < 0.5 && abs(vTexCoord.y - 0.5) < 0.5)`
> Restricted shader processing to the game screen area, fixing blurry cutoff point

- xbrz/shaders/xbrz-freescale-multipass/xbrz-freescale-pass0.slang
- xbrz/shaders/xbrz-freescale-multipass/xbrz-freescale-pass1.slang
- xbrz/shaders/xbrz-freescale.slang
- xbrz/xbrz-freescale-multipass.slangp
Adding these parameters lets users choose how much blending and interpolation happens. For example, setting the normal and dominant parameters to the same value but different from the none parameter rounds all corners.
This change has a small impact on performance--roughly 1-2% in my testing. I had originally parameterized the other macros, which have a more subtle effect, but the performance hit was more like 4-5%, which seemed a bit much for something that not many people are likely to mess with.
This PR alleviates the need for duplicating these shaders in https://github.com/libretro/slang-shaders/pull/344
> add parameters to xbrz-freescale and put multipass into a subdirectory

- crt/gtu-v050.slangp
- crt/shaders/gtu-v050/pass2.slang
As pointed out by zaksdf on reddit, the slang version was leaning on bilinear filtering in a way that was incorrect. I'm not sure why the GLSL version was unaffected, since it was _ported from the slang version_, but nevertheless, this should get it fixed up.
> Fix GTU-v50 to function like GLSL/Cg versions

- crt/crt-1tap.slangp
- crt/shaders/crt-1tap.slang
Goals of this shader:
- Be extremely lightweight and fast. The name is derived from the fact that it uses only a single texture lookup / "tap" per output pixel. It runs in <2 ms on an Intel HD 630 for 4k output of 240p input. The Intel HD 630 is a 6 year old integrated GPU. It runs in <1 ms for 4k output of 480p input on an NVIDIA GTX 1060 laptop.
- Be contrasty and sharp.
- Be easily and intuitively configurable.
- Be flexible for combination with other shaders. The shader behaves correctly under all kinds of input/output resolution combinations. The output is smoothly antialiased.
This shader runs about as fast as the existing crt-pi shader. It runs faster than crt-guest-advanced-fastest. I've compiled some comparison screenshots below.
Edit: Replaced one of the screenshots. There was …
> Add crt-1tap shader

- hdr/shaders/crt-sony-megatron-source-pass.slang
- hdr/shaders/crt-sony-megatron.slang
- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/gamma_correct.h
- hdr/shaders/include/parameters.h
Reintroduced all the correct OETF and EOTF functions for all the Rec. standards
Added gamma cut off values so people can adjust the gamma switch over point between equations as the standards define Refactored the parameters and broke out values to be more clear
>  V5.5 Sony Megatron Shader

- crt/shaders/crt-1tap.slang
- Update license
- Better defaults
- Don't compute alpha.
> Update crt-1tap to v1.1

- crt/shaders/newpixie/newpixie-crt.slang
An option to control the vignetting of one of my favorite crt shader newpixie-crt
based on CybeREX works from the libretro forum:
https://forums.libretro.com/t/remove-wavy-distortion-newpixie-crt-shader/28929
https://forums.libretro.com/u/CybeREX
> add "Vignette" parameter for shader newpixie-crt

- crt/shaders/newpixie/newpixie-crt.slang
The spec states:
> This attribute is a 2D position in the form vec4(x, y, 0.0, 1.0);. Shaders should not try to extract meaning from the x, y. gl_Position must be assigned as:
> 
> `gl_Position = MVP * Position;`
Furthermore, the idiomatic way of covering the screen is using an oversized triangle, not two separate triangles like RetroArch does, wherein changing the position doesn't work. Invert the texture coordinate instead.
> newpixie: Don't flip geometry coordinates, flip texcoords.

- crt/shaders/crt-royale/src/geometry-functions.h
When border size is 0, a division by zero causes the border to become infinitely large. Special-case this.
This allows removing the border with the seemingly stricter Vulkan implementations. On OpenGL, I'm able to remove the border by setting the border darkness to zero, but that doesn't work with Vulkan, probably because of another NaN or Inf somewhere. This lets you do the logical thing and correctly set the border size to 0 with either API.
> crt-royale: Fix division by zero when border is 0.

- bezel/koko-aio/shaders/config.inc
The first corrects a glitch on amd+vulkan and the second seems still needed by preset creators
> Koko-aio: Re-enable mipmaps for bezel and wrap_mode in shader.

- blurs/gizmo-composite-blur.slangp
- blurs/shaders/gizmo-blur.slang
**Features:**
- uniform-nearest shader with parameterizable horizontal and vertical blur
- can be used to mimic horizontal composite effects and vertical software blur
- has a parameterizable colour bleeding option
https://forums.libretro.com/t/gizmo-blur-shader/41514
> Add gizmo-blur shader

- interpolation/shaders/uniform-nearest.slang
- interpolation/uniform-nearest.slangp
**Features:**
- produces nearest neighbor look with fractional scales.
- uses texture AA shader code.
- uses hotizontal subpixel scaling.
- due to different pixel sizes, moving sprites change dimension if nearest neighbor is used with fractional scaling. This looks unsteady. This shader uniforms pixel dimensions. Output looks much quieter.
https://forums.libretro.com/t/uniform-nearest-interpolation-shader/41492
> Add uniform-nearest shader

- misc/grade-no-LUT.slangp
- misc/grade.slangp
- misc/shaders/glass.slang
- misc/shaders/grade-no-LUT.slang
'Glass' sees an update while 'grade' is a refactor. More consistent coeffs and white point adjustment function, also better and cleaner code.
Additionally a grade-no-LUT version is supplied with noop defaults, for those who want to quickly experiment with color adjustments.
> Update Grade and Glass

- misc/shaders/grade-no-LUT.slang
- misc/shaders/grade.slang
- Parameter reordering
- Add CRT flare feature (now you can emulate both surround nits and CRT glass refl %)
- Add Gamut Compression feature
- Change default for WhitePoint to 8500K
- Add 8-bit quantization on the composite signal pipeline
- Remove range conversion functions (now done within model conversion)
> Grade 2023 - Update

- blurs/dual_filter_2_pass.slangp
- blurs/dual_filter_4_pass.slangp
- blurs/dual_filter_6_pass.slangp
They were broken during adding the bloom shader when I refactored the file names and file structure.
> Fix broken shader paths for dual filter presets

- border/shaders/blur_fill/compose.slang
- border/shaders/blur_fill/parameters.slang
- border/shaders/blur_fill/render_sampling_areas.slang
The glcore slang compiler did not seem to like the overload of `min()`, so I changed the function to a different name to disambiguate.
> Fix bug with glcore driver of blur fill shader

- misc/shaders/grade-no-LUT.slang
- misc/shaders/grade.slang
- P3-D65 now uses 1886 EOTF
- Mask for GamutCompression is now CRT Gamma adjusted instead of 2.4 constant
- Fix uninitialized 'm_in' variable
- Treat Rec2020 as an EOTF -1886- (was being considered as an OETF)
- Optimize Dark_to_Dim
- Cosmetics
> Grade - Update + Cosmetics

- blurs/gauss_4tap.slangp
- blurs/shaders/gauss_4tap/common.slang
- blurs/shaders/gauss_4tap/gauss_2tap_h.slang
- blurs/shaders/gauss_4tap/gauss_2tap_v.slang
- blurs/shaders/gauss_4tap/parameters.slang
- border/blur_fill.slangp
- border/blur_fill_stronger_blur.slangp
- border/blur_fill_weaker_blur.slangp
- border/shaders/average_fill/compose.slang
- border/shaders/blur_fill/compose.slang
- border/shaders/blur_fill/parameters.slang
- border/shaders/blur_fill/render_sampling_areas.slang
This includes the changes of https://github.com/libretro/slang-shaders/pull/456 (this branch is based on the other one).
> Fix blur fill shimmering

- interpolation/pixel_aa.slangp
- interpolation/shaders/pixel_aa.slang
This shader offers a superset of features of the "pixellate" shader, and can produce the same output with certain parameters.
Features:
- Sharp upscaling with anti-aliasing
- Subpixel upscaling
- Sharpness can be controlled
- Gamma correct blending
- Integer scales result in pixel-perfect scaling
- Can use bilinear filtering for max. performance
With sharpness = 1.0, using the same gamma-correct blending, and disabling subpixel anti-aliasing, results are identical to the "pixellate" shader.
> Add Pixel AA interpolation shader

- interpolation/shaders/pixel_aa.slang
There was an oversight in the implementation that led to slightly blurry subpixel sampling.
This also fixes perfect integer scaling when subpx. sampling is turned on.
> Fix subpixel AA in pixel AA shader

- hdr/shaders/crt-sony-megatron-source-pass.slang
- hdr/shaders/include/colour_grade.h
- hdr/shaders/include/parameters.h
Added the differing phosphor sets - these override the standards primaries set by the colour system
Moved the settings around a bit to highlight the peak luminance and paper white luminance a bit more
> V5.6 Sony Megatron Shader

- misc/shaders/grade-no-LUT.slang
- misc/shaders/grade.slang
- Automatic compensation for black lift in 1886a gamma function, use instead "Black Level" to raise or lower blacks as usual
- Automatic gamma compensation given the new normalized black
- "Black Level" now is deterministic and given in 8-bit values. +10 means blacks will be lifted 10 point values for any gamma output
- Optimization. Now if signal type is RGB, phosphors + color space are sRGB and temperature ~6500K then the wp_adjust() function will be bypassed
> Grade - Update + Features + Fixes. Click for log

- border/shaders/average_fill/compose.slang
- border/shaders/average_fill/crop_and_sample_common.slang
- border/shaders/average_fill/parameters.slang
- border/shaders/blur_fill/compose.slang
- border/shaders/blur_fill/parameters.slang
- border/shaders/blur_fill/render_sampling_areas.slang
- misc/shaders/crop_and_scale/crop_and_scale.slang
- misc/shaders/crop_and_scale/parameters.slang
- rename scaling to crop and scale
- organize uniforms in *_fill consistently
- refactor common crop and scale parameters into separate file
- add overscale option.
> Scaling: Add overscale option

- handheld/console-border/shader-files/gb-pass1.slang
Fixes #70 by masking the LCD area at the end of gb-pass1.slang
> Hide garbage in Game Boy borders

- handheld/console-border/shader-files/border-auto-scale.slang
- handheld/console-border/shader-files/gb-pass-5.slang
This adds a simple feature to be able to darken the border.
It might be particularly useful for OLED users worried about burn-in, or users who think the border is too distracting at full brightness.
> Add handheld border brightness parameter

- handheld/gameboy-color.slangp
- handheld/gameboy-dark-mode.slangp
- handheld/gameboy-light-mode.slangp
- handheld/shaders/gameboy/shader-files/gb-pass0.slang
- misc/shaders/image-adjustment.slang
@hizzlekizzle - Updated based on your feedback.
- Added 'invert colors' as a parameter to 'image-adjustment'.
- I kept gameboy-light-mode and gameboy-dark-mode as separate presets. I think this makes more sense to the end user. They all reference the same shader files but with different background and palette parameters.
- Game Boy Color preset now references the original handheld/gameboy shader files. I modified gb-pass0 to support color based on a toggle.
> Game Boy Color / Light and Dark Mode Game Boy / Invert Colors

- downsample/mixed-res/hooks/README.md
- downsample/mixed-res/hooks/mixed-res-4x-append.slangp
- downsample/mixed-res/hooks/mixed-res-4x-prepend.slangp
- These prepend and append preset hooks can be used with almost any crt shaders. Instructions on how to use in readme.md.
- Enable downsampling with almost any shader.
> Add mixed-res preset hooks

- misc/geom.slangp
- misc/shaders/geom.slang
- A modified CRT-Geom without CRT features made to be appended/integrated into any other shaders and provide curvature/warping/oversampling features.
> Add Geom shader

- crt/shaders/crt-geom-mini.slang
- crt/shaders/crt-pocket.slang
not tested crt-pocket (cannot reproduce the error) but should work. crt-geom-mini now almost matches crt-geom and 3x faster.
> crt-geom-mini update from glsl, crt-pocket fix clamp error

- crt/shaders/crt-royale/src/crt-royale-bloom-approx.h
- It wasn't outputting the correct shader calculations and just spitting input colors;
- This bug only causes a slightly sharpening of final picture, so I understand that it passed unnoticed through porting.
> Fix a 7-year old bug in crt-royale-bloom-approx.h

- crt/shaders/crt-royale/src-fast/bind-shader-params.h
- presets/crt-royale-ntsc-composite-fast.slangp
- presets/crt-royale-pvm-blend.slangp
- presets/crt-royale-pvm-ntsc-composite.slangp
- presets/crt-royale-pvm-shmup.slangp
- presets/crt-royale-pvm.slangp
- Better uneven scanlines at non-integer scalings.
> Update crt-royale-fast and its presets

- Makefile
* Don't use the `-t` option of `cp`, which is not available on all platforms/environments
* Don't copy the entire contents of `.git` and the CI routines
Noticed these issues while doing some downstream work for ares pulling down the shaders.
> build: Enable building cross-platform; don't install git history

- Makefile
Instead of deleting .gitlab-ci.yml after installing into INSTALLDIR, the target tried to delete gitlab-ci.yml (without dot).
> build: fix .gitlab-ci.yml removal

- anamorphic/shaders/anamorphic.slang
Apparently "exp" was getting reflected as something weird. Changing it to literally anything else makes it work just fine.
> fix anamorphic on d3d12

- subframe-bfi/shaders/crt-beam-simulator.slang
> make LCD retention compensation optional

- bezel/Mega_Bezel/shaders/hyllian/crt-super-xbr/crt-hyllian-sinc-curvature.slang
- crt/shaders/crt-lottes-multipass/bloompass-glow.slang
- crt/shaders/crt-lottes-multipass/bloompass.slang
- crt/shaders/crt-lottes-multipass/scanpass-glow.slang
- crt/shaders/crt-lottes-multipass/scanpass.slang
- crt/shaders/crt-super-xbr/crt-custom.slang
- crt/shaders/hyllian/crt-hyllian-pass0.slang
- crt/shaders/hyllian/crt-hyllian-pass1.slang
- crt/shaders/hyllian/crt-hyllian-sinc-pass0.slang
- downsample/mixed-res/hooks/mixed-res-4x-append.slangp
- downsample/shaders/mixed-res/cheap-sharpen-tweaked.slang
- edge-smoothing/eagle/shaders/2xsai.slang
- edge-smoothing/xsal/shaders/2xsal-level2-xbr.slang
- handheld/shaders/color/gba-color-old.slang
- handheld/shaders/color/gbc-dev.slang
- nes_raw_palette/shaders/cgwg-famicom-geom/crt-geom-famicom.slang
- sharpen/shaders/cheap-sharpen.slang
- test/decode-format.slang
This should fix all of the ones listed in https://github.com/libretro/slang-shaders/issues/666 except for the one koko-aio preset and the noncausal feedback test shader that breaks intentionally.
> fix a bunch of shaders that break on d3d12

- subframe-bfi/shaders/crt-beam-simulator.slang
@blurbusters
FYI, ~~I unrolled the loop~~ moved the iterator out of the swizzle for 'result', which makes it able to compile on HLSL/d3d, and I added a runtime parameter to move the raster when people turn off the slew. That way they can position any lingering line artifacts in the least obtrusive manner for them.
> fix on d3d and add parameter to move raster

- handheld/authentic_gbc_single_pass.slangp
- handheld/shaders/authentic_gbc/authentic_gbc_single_pass.slang
- handheld/shaders/authentic_gbc/parameters.inc
- handheld/shaders/authentic_gbc/to_lin.slang
- handheld/shaders/authentic_gbc/to_lin_fast.slang
- pixel-art-scaling/shaders/pixel_aa/parameters.inc
- pixel-art-scaling/shaders/pixel_aa/pixel_aa_fast.slang
- pixel-art-scaling/shaders/pixel_aa/pixel_aa_single_pass.slang
- pixel-art-scaling/shaders/pixel_aa/shared.inc
- pixel-art-scaling/shaders/pixel_aa/to_lin.slang
- pixel-art-scaling/shaders/pixel_aa/to_lin_fast.slang
Brings back some changes from https://github.com/libretro/glsl-shaders/pull/506 to Slang.
(Thanks for merging these so quickly! This should hopefully be the last of these ping-pong PRs to maintain these Slang and GLSL shaders.)
> Authentic GBC v2.2

- anti-aliasing/fxaa+linear.slangp
Sample image:
Old FXAA preset at 1x: (this looks fine)
Old FXAA preset at 4x: (notice the strange edges)
New FXAA preset at 1x: (looks the same as old at 1x)
New FXAA preset at 4x:
Also added a preset with bilinear as a final pass (4x):
> fix fxaa preset

- handheld/gameboy-advance-dot-matrix-sepia.slangp
- handheld/shaders/gameboy/shader-files/gb-pass4.slang
- presets/gameboy-advance-dot-matrix-sepia.slangp
By default, both 'screen_offset' values are now -1.0 to eliminate the 1px line on the left and top of the image when using integer scaling mode with the gameboy shaders. This is hard to take a screenshot of, but use any of the 'gameboy' shaders and turn 'Integer Scaling' on to see the issue.
Uses the 'gameboy-pocket' and 'gameboy-color-dot-matrix' background to create a sepia tone image. 
_'gameboy-advance-dot-matrix-sepia'_
_'gameboy-advance-dot-matrix'_
> Updated 'screen_offset' and added 'gameboy-advance-dot-matrix-sepia'

- edge-smoothing/xbr/hybrid-jinc2-xbr-lv2.slangp
- edge-smoothing/xbr/shaders/jinc2-bilateral-xbr.slang
- At last got bilateral filter to combine jinc2 with xBR making a hybrid output;
- Posterization is reversed, because bilateral favors jinc2 on low gradient regions and xbr on high gradient ones.
- This approach can be used with any other edge smothing shader, though I couldn't get anything better than this.
> Add hybrid-jinc2-xbr-lv2 shaders

- interpolation/b-spline-4-taps-fast.slangp
- interpolation/bicubic-6-taps-fast.slangp
- interpolation/catmull-rom-6-taps-fast.slangp
- interpolation/lanczos2-6-taps-fast.slangp
- interpolation/shaders/bicubic/b-spline-2-taps-x.slang
- interpolation/shaders/bicubic/b-spline-2-taps-y.slang
- interpolation/shaders/bicubic/bicubic-3-taps-x.slang
- interpolation/shaders/bicubic/bicubic-3-taps-y.slang
- interpolation/shaders/bicubic/catmull-rom-3-taps-x.slang
- interpolation/shaders/bicubic/catmull-rom-3-taps-y.slang
- interpolation/shaders/lanczos/lanczos2-3-taps-x.slang
- interpolation/shaders/lanczos/lanczos2-3-taps-y.slang
- Add b-spline, bicubic, catmull-rom and lanczos2 in separate dimensions and using linear trick to get minimum number of texture lookups per dimension.
> Update Interpolation folder

- crt/shaders/crt-yah/crt-yah.fs.h
This PR corrects another edge case when using manual scanlines offset/jitter with automatic down-scaled image.
> CRT-Yah: Correct manual scanlines offset for auto down-scale

- crt/shaders/crt-yah/common/frame-helper.h
This PR fixes the below shader compile error occurring in older Retro Arch versions, where the `FrameTimeDelta` uniform is not available.
> [ERROR] [slang]: Unknown semantic found.
> [ERROR] [slang]: Failed to reflect SPIR-V. Resource usage is inconsistent with expectations.
Tested with Retro Arch v1.16.0
> Fix for older Retro Arch version without frametime uniforms

- edge-smoothing/xbr/super-xbr-fast.slangp
- edge-smoothing/xbr/super-xbr.slangp
I think that was the intention behind #697.
Note that retroarch default to false for invalid boolean https://github.com/libretro/RetroArch/blob/master/libretro-common/file/config_file.c#L1205
So technically to keep current behaviour it should be `false` but since @Hyllian put `linear`there I presume the intention is `true`.
(Noticed this since the non-boolean is tripping up librashader)
> Use boolean for updated super-xbr shaders

- crt/crt-CreativeForce-Arcade.slangp
- crt/crt-CreativeForce-SharpSmooth.slangp
- interpolation/lanczos16-AR.slangp
- interpolation/shaders/lanczos16-AR.slang
Quick fix to make sure the shaders open in nearest mode for best image quality. Only edited the 3 preset files, not the shaders themselves, aside from changing the default AR value for the lanczos16-AR shader.
> Fix all presets to nearest plus change AR value
