handheld/gba-color.slang

Translated gba-color.cg.

---

retro/shaders/aann.slang

Update to the latest code from Wareya:
http://board.byuu.org/phpbb3/viewtopic.php?p=28312#p28312
[Output example](https://a.pomf.cat/ugtozr.png)

(AANN) Update to latest version

---

xbr/shaders/super-xbr-2p.slangp
xbr/shaders/super-xbr/custom-jinc2-sharper.slang
xbr/shaders/super-xbr/super-xbr-params.inc
xbr/shaders/super-xbr/super-xbr-pass0.slang
xbr/shaders/super-xbr/super-xbr-pass1.slang
xbr/shaders/super-xbr/super-xbr-pass2.slang

Final image doesn't seem to be quite right - horizontal lines are bumpy.
@Hyllian - Hi, take a look, you got any ideas why the picture isn't quite right?

Translated all of the shaders to allow the super-xbr-2p preset to work.

---

handheld/gameboy/shader-files/gb-pass0.slang
handheld/gameboy/shader-files/gb-pass1.slang
handheld/gameboy/shader-files/gb-pass2.slang
handheld/gameboy/shader-files/gb-pass3.slang
handheld/gameboy/shader-files/gb-pass4.slang

gb shader formatting quality assurance

---

crt/shaders/crtglow_gauss.slangp
crt/shaders/crtglow_gauss_ntsc_3phase.slangp
crt/shaders/crtglow_lanczos.slangp
crt/shaders/glow/blur_horiz.slang
crt/shaders/glow/blur_params.inc
crt/shaders/glow/blur_vert.slang
crt/shaders/glow/gauss_horiz.slang
crt/shaders/glow/gauss_vert.slang
crt/shaders/glow/lanczos_horiz.slang
crt/shaders/glow/linearize.slang
crt/shaders/glow/resolve.slang
crt/shaders/glow/threshold.slang

(crtglow) Translated the glow set of shaders and their associated

---

pal/pal-singlepass.slang

Tried to add the phase noise feature found in his crt.py software
version.
@svofski - Hi. I couldn't find anything in your repo about your GLSL shaders's licenses. Any choices?

(pal) Port @svofski's CRT shader to libretro.

---

crt/shaders/crt-lottes-multipass/crt-lottes-multipass.slang
crt/shaders/crt-lottes-multipass/horz3minus1.slang
crt/shaders/crt-lottes-multipass/horz3plus1.slang
crt/shaders/crt-lottes-multipass/horz5.slang
crt/shaders/crt-lottes-multipass/horz5minus2.slang
crt/shaders/crt-lottes-multipass/horz5plus2.slang
crt/shaders/crt-lottes-multipass/horz7.slang
crt/shaders/crt-lottes-multipass/horz7minus1.slang
crt/shaders/crt-lottes-multipass/horz7plus1.slang
crt/shaders/crt-lottes-multipass/linearize.slang

Also converted some divisors into multiplicands.

(crt-lottes-multipass) Style nits

---

crt/common.inc
crt/cubic.slang
crt/linearize.slang
crt/parameters.inc
crt/scanline.slang
crt/sinc.slang
spec/SHADER_SPEC.md

Trying it this way to see if Github lets you do this...

Merge upstream changes

---

crt/shaders/crt-cgwg-fast.slang
crt/shaders/crt-easymode.slang
crt/shaders/crt-hyllian.slang
crt/shaders/crt-lottes.slang
crt/shaders/glow/gauss_vert.slang
crt/shaders/glow/linearize.slang
crt/shaders/glow/resolve.slang
crt/shaders/glow/threshold.slang
pal/pal-singlepass.slang

Fixed a bug (introduced when porting to slang) related
to crt-hyllian and the PHOSPHOR feature.

Added parameters to all modified files.

---

retro/retro-v2.slangp
retro/shaders/retro-v2.slang

Tried to muck around to see if I could get rid of the pixel sheen but wasn't lucky.

(retro) Ported retro-v2 and the respective preset.

---

presets/crt-lottes-trinitron.slangp

We're only human. Now it loads for me.

(lottes-trinitron) Fix path of shader5

---

handheld/console-border/dmg-2x.slangp
handheld/console-border/dmg-3x.slangp
handheld/console-border/dmg-4x.slangp
handheld/console-border/dmg-5x.slangp
handheld/console-border/dmg-6x.slangp
handheld/console-border/gb-pocket-2x.slangp
handheld/console-border/gb-pocket-3x.slangp
handheld/console-border/gb-pocket-4x.slangp
handheld/console-border/gb-pocket-5x.slangp
handheld/console-border/gb-pocket-6x.slangp
handheld/shaders/gameboy/shader-files/gb-pass0.slang

See https://github.com/libretro/glsl-shaders/pull/20

GB borders new default and additions.

---

reshade/shaders/LUT/LUT.slang

See https://github.com/libretro/glsl-shaders/pull/26

(LUT) Clamp to highest possible value

---

anti-aliasing/shaders/aa-shader-4.0.slang
crt/shaders/crt-easymode.slang
crt/shaders/crt-lottes-multipass/bloompass.slang
crt/shaders/crt-lottes-multipass/scanpass.slang
crt/shaders/crt-lottes.slang
crt/shaders/crt-royale/src/crt-royale-bloom-approx.h
crt/shaders/crt-royale/src/crt-royale-mask-resize-horizontal.slang
crt/shaders/crt-slangtest/sinc.slang
crt/shaders/glow/gauss_vert.slang
crt/shaders/glow/linearize.slang
crt/shaders/glow/resolve.slang
crt/shaders/glow/threshold.slang
dithering/shaders/mdapt/passes/mdapt-pass0.slang
dithering/shaders/mdapt/passes/mdapt-pass1.slang
dithering/shaders/mdapt/passes/mdapt-pass3.slang
dithering/shaders/mdapt/passes/mdapt-pass4.slang
pal/shaders/pal-singlepass.slang
retro/shaders/aann.slang
scalefx/shaders/old/scalefx-pass1.slang
scalefx/shaders/scalefx-pass2.slang

In particular, a number of identifiers were renamed for better compatibility with Metal

Various fixes to for improved SPIRV-Cross compatibility

---

handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color-4k.slang
handheld/shaders/simpletex_lcd/simpletex_lcd+gba-color.slang
handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color-4k.slang
handheld/shaders/simpletex_lcd/simpletex_lcd+gbc-color.slang

This is just the slang version of `glsl-shaders` [PR #85](https://github.com/libretro/glsl-shaders/pull/85)

(simpletex_lcd) Update colour correction values

---

retro/shaders/sharp-bilinear-scanlines.slang
retro/shaders/sharp-bilinear-simple.slang
retro/sharp-bilinear-2x-prescale.slangp
retro/sharp-bilinear-scanlines.slangp
retro/sharp-bilinear-simple.slangp

For more information, see
https://github.com/rsn8887/Sharp-Bilinear-Shaders
Ready to merge!

add sharp-bilinear-simple, -scanlines and -2x-prescale shaders

---

procedural/mudlord-imsosorry.slang

This might be unexpected for....several reasons which will remain not publically known.
But here is a shader I did for flashback 2019. it works best with my VHS/PAL post process shader.
The shader is the core to:
[![im so sorry](http://img.youtube.com/vi/NZv369YHLt4/0.jpg)](https://www.youtube.com/watch?v=NZv369YHLt4 "im so sorry")

add my shader from FB2019.

---

presets/mdapt+fast-bilateral+super-4xbr+scanlines.slangp

It's working, I tested it. Works much faster compared to my hand-made GLSL preset.

Add mdapt+fast-bilateral+super4xbr+scanlines preset.

---

misc/grade.slang

More accurate colors/function as it draws the daylight locus in CIE xy space.

grade - compute white point in CIExy

---

misc/grade.slang

and sorry for the extra commit >.<

grade - offset temperature to D65

---

anamorphic/anamorphic.slangp
anamorphic/shaders/anamorphic.slang

allows to correct a stretched content approaching correct aspect ratio

anamorphic widescreen correction shader

---

misc/grade.slang

Updating grade.slang with the  changes of the last months, mainly a full gamma pipeline rework and an improved white_point/temperature function. glsl will come later if everything is fine so far with slang.

grade.slang - gamma and temperature rework

---

ntsc/shaders/ntsc-adaptive-tate/ntsc-tate-pass1.slang

The preset was updated but not the shader itself.

parameterize ntsc-tate as ntsc-adaptive was

---

crt/crt-sony-pvm-20L4-4k-hdr.slangp
crt/crt-sony-pvm-2730-4k-hdr.slangp
crt/crt-sony-pvm-4k-hdr.slangp
crt/shaders/crt-sony-pvm-4k-hdr.slang

Made default shader more like a Sony PVM 2730 with a slightly softer image than the 20L4 
Added two new slangp configs that represent a Sony PVM 2730 and a Sony PVM 20L4 
Removed defunct shader parameters 
Added sharpness parameter 
Cleaned up shader a little

Made default shader more like a Sony PVM 2730

---

hdr/shaders/crt-sony-pvm-4k-hdr.slang

Fixed BGR 
Fixed scaling instructions 
Broke up horizontal attributes into their own channels i.e we now have horizontal beam characteristics 
Dabbled with values accordingly

V2.2 Sony PVM 4K HDR Shader

---

hdr/crt-viewsonic-A90f+-4k-hdr.slangp
hdr/crt-viewsonic-superclear-4k-hdr.slangp
hdr/shaders/crt-aperture-grille-hdr.slang
hdr/shaders/crt-shadow-mask-hdr.slang
hdr/shaders/crt-slot-mask-hdr.slang
hdr/shaders/include/developer_parameters.h
hdr/shaders/include/developer_properties.h

Added Viewsonic SuperClear A90f+ simulation 
dded numerous shadow masks

V3.2 Sony PVM 4K HDR Shader

---

hdr/crt-arcade-4k-hdr.slangp
hdr/crt-jvc-professional-4k-hdr.slangp
hdr/crt-jvc-professional-TM-H1950CG-4k-hdr.slangp
hdr/crt-sammy-atomiswave-4k-hdr.slangp

Added Sammy Atomiswave simulation preset 
Added JVC Professional TM-H1950CG simulation preset

V3.3 Sony PVM 4K HDR Shader

---

hdr/shaders/crt-hdr.slang
hdr/shaders/include/scanline_generation.h

Standardized the code to the general RetroArch shaders

V4.2 Sony PVM 4K HDR Shader

---

hdr/crt-sony-pvm-4k-hdr.slangp
hdr/shaders/crt-hdr.slang
hdr/shaders/include/colour_grade.h

Added gamma, brightness and contrast controls

V5.1 Sony PVM 4K HDR Shader

---

hdr/crt-sony-pvm-4k-hdr.slangp
hdr/shaders/crt-hdr.slang
hdr/shaders/include/colour_grade.h
hdr/shaders/include/scanline_generation.h

Added SDR mode 
Added saturation colour grade 
Fixed sony pvm shader brightness

V5.5 Sony PVM 4K HDR Shader

---

hdr/crt-sony-megatron-arcade.slangp
hdr/crt-sony-megatron-bang-olufsen.slangp
hdr/crt-sony-megatron-jvc-professional.slangp
hdr/crt-sony-megatron-sony-pvm.slangp
hdr/crt-sony-megatron-toshiba-microfilter.slangp
hdr/crt-sony-megatron-viewsonic-superclear.slangp
hdr/shaders/crt-sony-megatron-hdr-pass.slang
hdr/shaders/crt-sony-megatron-source-pass.slang
hdr/shaders/crt-sony-megatron.slang
hdr/shaders/include/colour_grade.h
hdr/shaders/include/inverse_tonemap.h
hdr/shaders/include/parameters.h
hdr/shaders/include/scanline_generation.h

Optimised sony megatron shader by adding a three stage process and colour grading at lower source resolution
Fixed include path slashes

V1.2 Sony Megatron Shader

---

hdr/crt-sony-megatron-aeg-CTV-4800-VT-hdr.slangp
hdr/shaders/crt-sony-megatron.slang

Added NTSC support to 'crappy tv' preset otherwise known as the AEG CTV-4800-VT

V2.7 Sony Megatron Shader

---

xbr/shaders/support/b-spline.slang
xbr/shaders/xbr-lv1.slang
xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass0.slang
xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass1.slang
xbr/shaders/xbr-lv3.slang
xbr/xbr-lv1.slangp
xbr/xbr-lv2-multipass.slangp
xbr/xbr-lv3-9x.slangp
xbr/xbr-lv3.slangp

- New color distance function to improve IQ;
- Merge noblend and aa shaders in same files;
- Better param descriptions;
- New param to switch between noblend and aa;
- New lv1, lv2-multipass and lv3-9x.

Update main xBR shaders

---

xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass0.slang
xbr/shaders/xbr-lv3-multipass/xbr-lv3-pass0.slang
xbr/shaders/xbr-lv3-multipass/xbr-lv3-pass1.slang
xbr/shaders/xbr-lv3-multipass/xbr-lv3-pass1b.slang
xbr/xbr-lv3-9x-multipass.slangp
xbr/xbr-lv3-multipass.slangp

These are much faster than the standalone versions.

Add xbr-lv3-multipass and lv3-9x-multipass

---

ddt/ddt-xbr-lv1.slangp
ddt/shaders/ddt-xbr-lv1.slang

Merge xbr edge detection with sharpness control and triangulation from DDT.

Add ddt-xbr-lv1 shaders

---

cubic/bicubic-fast.slangp
cubic/shaders/bicubic-x.slang
cubic/shaders/bicubic-y.slang

- Bicubic shaders in two passes, very fast.

Add bicubic-fast shaders

---

ddt/ddt-jinc-linear.slangp
ddt/ddt-jinc.slangp
ddt/shaders/ddt-jinc.slang

- A hybrid between DDT and Jinc2 shader;
- On diagonal edges it behaves like DDT, otherwise like Jinc2;
- Added a linear gamma preset too.

Add DDT-Jinc shaders

---

anti-aliasing/advanced-aa.slangp
eagle/2xsai.slangp
eagle/super-2xsai.slangp
hqx/hq2x.slangp
hqx/hq3x.slangp
hqx/hq4x.slangp
scalehq/2xScaleHQ.slangp
scalehq/4xScaleHQ.slangp
xbrz/2xbrz-linear.slangp
xsal/2xsal.slangp
xsoft/4xsoft.slangp
xsoft/4xsoftSdB.slangp

- Swap stock linear by cubic multipass shaders.
- Improves IQ for 4xSoft, 2xSaL, 2xSacaleHq, 4xScaleHq, HQ2x, HQ3x, HQ4x, 2xBRz, 2xSaI, Super-2xSaI and Advance2x-AA.

Improves smooth shaders presets

---

handheld/retro-v2-nds-color.slangp
handheld/retro-v3-nds-color.slangp
handheld/retro-v3.slangp
handheld/shaders/retro-v2.slang
handheld/shaders/retro-v3.slang

- Add Retro-V3 shader
- Add Retro-V3-nds-colors and Retro-V2-nds-colors

Add Retro-V3 shaders

---

hdr/shaders/crt-sony-megatron.slang
hdr/shaders/include/parameters.h

Added 1080p masks
Added OLED mask support

V3.4 Sony Megatron Shader

---

hdr/shaders/crt-sony-megatron.slang

Fixed 300TVL 4K aperture grille mask

V3.4.1 Sony Megatron Shader

---

crt/shaders/yee64.slang
crt/shaders/yeetron.slang

Which means its now humanly readable!
Hooray for reverse engineer!

CRt-Yee64 and yeetron now uses RSDK Decompilation code

---

denoisers/crt-fast-bilateral-super-xbr.slangp

Fix issue #280

---

dithering/checkerboard-dedither.slangp
dithering/shaders/checkerboard-dedither/checkerboard-dedither-pass1.slang
dithering/shaders/checkerboard-dedither/checkerboard-dedither-pass2.slang
dithering/shaders/checkerboard-dedither/checkerboard-dedither-pass3.slang
dithering/shaders/checkerboard-dedither/linearize.slang

- Smooths checkerboard dithering.

Add Chckerboard-Dedither shader

---

handheld/retro-tiles.slangp
handheld/shaders/retro-tiles.slang

A shader designed for handheld and low res systems. It turns pixels into crisp tiles.

Add Retro-Tiles shaders

---

blurs/sharpsmoother.slangp
blurs/smart-blur.slangp

Added presets for sharpsmoother and smart-blur so they can be easily tested by users

Added presets for sharpsmoother and smart-blur

---

crt/crt-gdv-mini.slangp
crt/shaders/crt-gdv-mini.slang

Added Slang version of crt-gdv-mini

Added Slang version of crt-gdv-mini

---

crt/crt-nobody.slangp
crt/shaders/crt-nobody.slang

- First release.
- A fast crt shader intended for potato devices.

Add crt-nobody shader

---

crt/shaders/zfast_crt/zfast_crt_composite.slang
crt/zfast-crt-composite.slangp

Adds the Zfast Composite shader converted from the GLSL repository.

Add Zfast Composite shader

---

bezel/Mega_Bezel/README.md
bezel/Mega_Bezel/shaders/ShaderTodo.txt
bezel/Mega_Bezel/shaders/base/common/params-0-screen-scale.inc
bezel/Mega_Bezel/shaders/base/common/params-2-reflection.inc
bezel/Mega_Bezel/shaders/base/text.inc
bezel/Mega_Bezel/shaders/guest/hsm-afterglow0.slang
bezel/Mega_Bezel/shaders/guest/hsm-avg-lum.slang
bezel/Mega_Bezel/shaders/guest/hsm-bloom_horizontal.slang
bezel/Mega_Bezel/shaders/guest/hsm-crt-guest-advanced-ntsc-pass1.inc
bezel/Mega_Bezel/shaders/guest/hsm-crt-guest-advanced-ntsc-pass2.inc
bezel/Mega_Bezel/shaders/guest/hsm-crt-guest-advanced-ntsc.slang
bezel/Mega_Bezel/shaders/guest/hsm-crt-guest-advanced.inc
bezel/Mega_Bezel/shaders/guest/hsm-deconvergence.inc
bezel/Mega_Bezel/shaders/guest/hsm-interlace-and-linearize.slang
bezel/Mega_Bezel/shaders/guest/hsm_crt-guest-advanced-release-version.txt
bezel/Mega_Bezel/shaders/megatron/crt-sony-megatron-source-pass.slang

Changes:
* Updated guest to crt-guest-advanced-2022-10-11-release1 with new halation
* Fixed Compilation issues with GLCore
* Fix error in Megatron which was preventing it from loading
* Fixed problem with NO-REFLECT where you could see the background through where the black edge was supposed to be

Mega Bezel is updated to V1.5.0_2022-10-11

---

handheld/console-border/gba-agb001-color-motionblur.slangp
handheld/console-border/gba-ags001-color-motionblur.slangp
handheld/console-border/gba-lcd-grid-v2.slangp
handheld/console-border/gba.slangp
handheld/console-border/gbc-lcd-grid-v2.slangp
handheld/console-border/shader-files/border-auto-scale.slang

This should help users on how to change scale for presets using the new `border-auto-scale.slang` shader.

Instructions on how to change scale for border-auto-scale presets

---

hdr/shaders/crt-sony-megatron-sdr.slangp
hdr/shaders/include/colour_grade.h
hdr/shaders/include/parameters.h

Fixed gamma in to use the proper rec. 601 transfer function

V4.2 Sony Megatron Shader

---

hdr/shaders/crt-sony-megatron.slang

Fixed performance issues for slot masks on low power ARM devices like mobile android phones and android TV devices
Improved performance issues for shadow masks on low power ARM devices like mobile android phones

V5.0 Sony Megatron Shader

---

hdr/shaders/crt-sony-megatron.slang

Fixed performance issues for shadow masks on android devices - now runs at 60fps at 1440p on Snapdragon 865 (OnePlus 8 Pro)

V5.1 Sony Megatron Shader

---

presets/scalefx9-aa-blur-hazy-ntsc-sh1nra358.slangp
presets/scalefx9-aa-blur-hazy-vibrance-sh1nra358.slangp
scalefx/shaders/old/scalefx-9x.slangp
scalefx/shaders/old/scalefx.slangp

fix old scalefx reference passes in presets

---

crt/shaders/zfast_crt/zfast_crt_curvature.slang
crt/zfast-crt-curvature.slangp

This is z-fast with curvature added, requested by lasly

Added zfast_crt_curvature

---

sharpen/rca_sharpen.slangp
sharpen/shaders/rcas.slang

As proposed on Discord:
https://discord.com/channels/184109094070779904/584075942276628481/1071558564126138510
This implementation adds RCAS denoising, which can suppress certain artifacts. It is on by default. Some examples on Discord.

Add RCA sharpening

---

crt/crt-sines.slangp
crt/shaders/crt-sines.slang

Improved version of glsl shader.

add crt-sines

---

border/average_fill.slangp
border/shaders/average_fill/compose.slang
border/shaders/average_fill/crop_and_sample_bottom.slang
border/shaders/average_fill/crop_and_sample_common.slang
border/shaders/average_fill/crop_and_sample_left.slang
border/shaders/average_fill/crop_and_sample_right.slang
border/shaders/average_fill/crop_and_sample_top.slang
border/shaders/average_fill/parameters.slang

As requested and tested by Riggles on Discord.

Add average fill

---

border/shaders/average_fill/compose.slang
border/shaders/average_fill/parameters.slang
border/shaders/blur_fill/scaling.slang

Update average fill with the scaling and extended configuration options of blur fill.

Update average fill

---

border/shaders/average_fill/compose.slang
border/shaders/average_fill/parameters.slang
border/shaders/blur_fill/compose.slang
border/shaders/blur_fill/parameters.slang
border/shaders/blur_fill/render_sampling_areas.slang
border/shaders/blur_fill/scaling.slang

This fixes several inconsistencies and bugs, especially in relation to forced aspect ratio modes.
It also improves numerical accuracy a bit in theory.

Fix scaling in border fill shaders

---

misc/print-resolution.slangp
misc/shaders/print-resolution/print-resolution-apply.slang
misc/shaders/print-resolution/print-resolution-generate-and-cache.slang

New preset and shaders to print text on top of the game image passing through the chain

Print Resolution Text preset and shaders

---

blurs/gauss_4tap.slangp
blurs/shaders/gauss_4tap/common.slang
blurs/shaders/gauss_4tap/gauss_2tap_h.slang
blurs/shaders/gauss_4tap/gauss_2tap_v.slang
blurs/shaders/gauss_4tap/parameters.slang

Super simple Gaussian filtering, separated into two passes.
Same principle as `blurs\shaders\blur-gauss-h.slang`, but a coarser approximation with configurable sigma.
I will use this as a lowpass filter later.

Add gauss-4tap

---

misc/shaders/grade-no-LUT.slang
misc/shaders/grade.slang

- Adopted some GLES related formatting and 'type' consistency (still not compatible with GLES and not planned)
- Some notes on Phosphors
- Cosmetics

Grade - Formatting + Notes + Cosmetics

---

border/blur_fill.slangp
border/blur_fill_stronger_blur.slangp
border/blur_fill_weaker_blur.slangp
border/shaders/average_fill/compose.slang
border/shaders/average_fill/parameters.slang
border/shaders/blur_fill/compose.slang
border/shaders/blur_fill/parameters.slang
interpolation/shaders/pixel_aa/pixel_aa.slang
interpolation/shaders/pixel_aa/shared.slang

Suggest to squash commits before merge. :)

Optimize and simplify Pixel AA, Average Fill, and Blur Fill presets

---

crt/shaders/newpixie/newpixie-crt.slang

Hello
I would like to add a ghosting parameter for newpixie-crt
In some cases, the ghosting are too much visible for my eyes.

feat: Add ghosting parameter for newpixie-crt

---

crt/crt-Cyclon.slangp
crt/shaders/crt-Cyclon.slang

Did a mistake and pushed the glsl file i had in the same folder before, when porting it :P

add crt-Cyclon

---

edge-smoothing/cleanEdge/cleanEdge-scale.slangp
edge-smoothing/cleanEdge/shaders/cleanEdge-scale.slang
edge-smoothing/cleanEdge/shaders/cleanEdge.slang
include/cleanEdge.inc
pixel-art-scaling/cleanEdge-rotate.slangp
pixel-art-scaling/shaders/cleanEdge-rotate.slang

from torcado's algo, featured here: https://torcado.com/cleanEdge/

add cleanEdge shader with edge-smoothing and rotation presets

---

crt/crt-resswitch-glitch-koko.slangp
crt/shaders/crt-resswitch-glitch-koko.slang

https://forums.libretro.com/t/reproduce-the-noise-of-switching-resolution/43763/13

Add crt-resswitch-glitch-koko

---

ntsc/shaders/ntsc-adaptive/ntsc-pass2.slang

Phase 3 chroma is scaled correctly now.

Update Chroma Scaling.

---

ntsc/shaders/ntsc-adaptive/ntsc-pass1.slang

Add the param Artifacting Rainbow Effect.

Add Rainbow Effect to ntsc-adaptive

---

crt/newpixie-mini.slangp
crt/shaders/newpixie-mini/newpixie-mini.slang

This adds a new version of the fantastic NewPixie shader with lower GPU requeriments.
It removes accumulation/ghosting, but keeps the great looking color bleed, curvature, scanlines and shadow mask.

Add simplified/faster newpixie version.

---

crt/shaders/newpixie-mini/newpixie-mini.slang

Small adjustments to the newpixie-mini shader variation.

Newpixie-mini adjustments.

---

crt/shaders/newpixie-mini/newpixie-mini.slang

Remove some calculations that are not needed anymore.

Remove unused calculations.

---

interpolation/b-spline-4-taps.slangp
interpolation/catmull-rom-5-taps.slangp
interpolation/shaders/b-spline-4-taps.slang
interpolation/shaders/catmull-rom-5-taps.slang

Two standalone fast cubic shaders.

Add b-spline-4-taps and catmull-rom-5-taps

---

interpolation/bicubic-5-taps.slangp
interpolation/hermite.slangp
interpolation/shaders/bicubic-5-taps.slang
interpolation/shaders/hermite.slang

- Two standalone fast shaders.
* Hermite was never explicitly available, so I think it deserves a place. It's a slightly softer quilez shader.

Add bicubic-5-taps and hermite shaders

---

sharpen/cheap-sharpen.slangp
sharpen/shaders/cheap-sharpen.slang

A lightweight sharpen shader with anti-ringing.

Add cheap-sharpen shader

---

downsample/drez/drez_3ds_x-400_y-480.slangp
downsample/drez/drez_nds_x-256_y-384.slangp
downsample/drez/drez_psp_x-480_y-272.slangp
downsample/drez/drez_psp_x-960_y-544.slangp
downsample/drez/drez_psp_x-viewport_y-272.slangp
downsample/drez/drez_psp_x-viewport_y-544.slangp
downsample/drez/drez_x-1440_y-1080.slangp
downsample/drez/drez_x-1920_y-1080.slangp
downsample/drez/drez_x-320_y-224.slangp
downsample/drez/drez_x-320_y-240.slangp
downsample/drez/drez_x-640_y-480.slangp
downsample/drez/drez_x-viewport_y-224.slangp
downsample/drez/drez_x-viewport_y-240.slangp
downsample/drez/drez_x-viewport_y-320.slangp
downsample/drez/drez_x-viewport_y-480.slangp
downsample/drez_1x.slangp
downsample/shaders/drez-g-sharp_resampler.slang
misc/shaders/print-resolution/print-resolution-apply.slang
misc/shaders/print-resolution/print-resolution-generate-and-cache.slang

New drez downsampling presets
Improved print resolution so it scales with the framebuffer size

Added drez Downsampling and Updated Print Resolution

---

downsample/mixed-res-4x-jinc2.slangp
downsample/mixed-res/2x/mixed-res-bicubic.slangp
downsample/mixed-res/2x/mixed-res-bilinear.slangp
downsample/mixed-res/2x/mixed-res-jinc2.slangp
downsample/mixed-res/2x/mixed-res-lanczos3.slangp
downsample/mixed-res/2x/mixed-res-nnedi3-luma.slangp
downsample/mixed-res/2x/mixed-res-reverse-aa.slangp
downsample/mixed-res/2x/mixed-res-spline16.slangp
downsample/mixed-res/2x/mixed-res-super-xbr.slangp
downsample/mixed-res/3x/mixed-res-bicubic.slangp
downsample/mixed-res/3x/mixed-res-bilinear.slangp
downsample/mixed-res/3x/mixed-res-jinc2.slangp
downsample/mixed-res/3x/mixed-res-lanczos3.slangp
downsample/mixed-res/3x/mixed-res-nnedi3-luma.slangp
downsample/mixed-res/3x/mixed-res-reverse-aa.slangp
downsample/mixed-res/3x/mixed-res-spline16.slangp
downsample/mixed-res/3x/mixed-res-super-xbr.slangp
downsample/mixed-res/4x/mixed-res-bicubic.slangp
downsample/mixed-res/4x/mixed-res-bilinear.slangp
downsample/mixed-res/4x/mixed-res-lanczos3.slangp
downsample/mixed-res/4x/mixed-res-nnedi3-luma.slangp
downsample/mixed-res/4x/mixed-res-reverse-aa.slangp
downsample/mixed-res/4x/mixed-res-spline16.slangp
downsample/mixed-res/4x/mixed-res-super-xbr.slangp
downsample/shaders/mixed-res/blur-gauss-h.slang
downsample/shaders/mixed-res/blur-gauss-v.slang
downsample/shaders/mixed-res/cheap-sharpen-tweaked.slang
downsample/shaders/mixed-res/coder.slang
downsample/shaders/mixed-res/hires-tagger.slang
downsample/shaders/mixed-res/output.slang

- Add mixed-res shaders in downsample folder;
- Presets for 2x, 3x and 4x downsample added.

Add mixed-res shaders

---

interpolation/lanczos2-5-taps.slangp
interpolation/shaders/lanczos2-5-taps.slang

- Add lanczos2 using just 5 texture lookups.

Add lanczos2-5-taps

---

edge-smoothing/ddt/3-point.slangp
edge-smoothing/ddt/shaders/3-point.slang
misc/relief.slangp
misc/shaders/relief.slang

- Known N64 3-point texture filter, now in slang;
- Relief shader. Gives some bump to pixel art games.

Add n64 3-point and relief shaders

---

border/autocrop-koko.slangp
border/autocrop-koko.txt
border/shaders/autocrop-koko/autocrop0_precut.slang
border/shaders/autocrop-koko/autocrop1_compute.slang
border/shaders/autocrop-koko/autocrop2_display.slang
border/shaders/autocrop-koko/autocrop_config.inc

It seems to work well in koko-aio.
Please test ;)

Add autocrop-koko shader

---

film/film-grain.slangp
film/shaders/film-grain.slang

Add film-grain shader

---

warp/dilation.slangp
warp/shaders/dilation.slang

- Added a param to control better dilation. So, now it's a soft dilation.
- Added a preset useful to append another presets.

Update dilation shader

---

downsample/mixed-res/2x/mixed-res-super-xbr-film-full.slangp
downsample/mixed-res/2x/mixed-res-super-xbr-film.slangp
downsample/mixed-res/2x/mixed-res-super-xbr.slangp
downsample/mixed-res/3x/mixed-res-super-xbr-film-full.slangp
downsample/mixed-res/3x/mixed-res-super-xbr-film.slangp
downsample/mixed-res/3x/mixed-res-super-xbr.slangp
downsample/mixed-res/4x/mixed-res-super-xbr-film-full.slangp
downsample/mixed-res/4x/mixed-res-super-xbr-film.slangp
edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass0.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass1.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass2.slang
edge-smoothing/xbr/shaders/support/delinearize.slang
edge-smoothing/xbr/shaders/support/linearize.slang
edge-smoothing/xbr/super-xbr-fast.slangp
edge-smoothing/xbr/super-xbr.slangp

- Super-xbr go back to gamma color, as I think it looks better;
- Some parameters tweaked;
- New mixed-res presets.

Update super-xbr and mixed-res shaders

---

denoisers/bilateral.slangp
denoisers/shaders/bilateral.slang

- A flexible and fast bilateral shader from guest.r.

Add bilateral shader from guest.r

---

denoisers/bilateral-2p.slangp
denoisers/shaders/bilateral-horizontal.slang
denoisers/shaders/bilateral-vertical.slang

- Fast bilateral shaders in 2-pass from guest.r.

Add bilateral-2p shaders

---

deblur/deblur-luma.slangp
deblur/deblur.slangp
deblur/shaders/deblur-luma.slang
deblur/shaders/deblur.slang

- A faster deblur using luma instead color channels to calc contrast;
- Added a preset for deblur too;
- Small fix to deblur shader.

Add deblur-luma shaders

---

bezel/koko-aio/shaders-ng/config.inc
bezel/koko-aio/shaders-ng/in_glow_y.slang

koko-aio hotfix4

---

downsample/mixed-res-4x-crt-hyllian.slangp
downsample/shaders/mixed-res/output.slang

- Only 4x version for now;
- Curvature is broken in this preset. It'll be fixed in future updates.

Add mixed-res-crt-hyllian preset

---

crt/shaders/crt-consumer.slang
crt/shaders/crt-pocket.slang

https://github.com/libretro/slang-shaders/pull/517#issuecomment-2159399598

add licences

---

crt/shaders/zfast_crt/zfast_crt_geo.slang
crt/zfast-crt-geo.slangp

Add zfast_crt_geo shader

---

presets/crt-royale-ntsc-composite-fast.slangp

Uses fast royale and newer guest's adaptive.

Add crt-royale-ntsc-composite-fast preset

---

crt/shaders/hyllian/crt-hyllian-base.slang
crt/shaders/hyllian/support/glow/blur-glow-mask-geom.slang

Fix color clipping in crt-hyllian

---

pixel-art-scaling/edge1pixel.slangp
pixel-art-scaling/shaders/edge1pixel.slang

Ported to .slang from glsl-shaders (https://github.com/libretro/glsl-shaders/pull/489)

Add shader for smoothing hard pixel edges.

---

pixel-art-scaling/edgeNpixels.slangp
pixel-art-scaling/shaders/edge1pixel.slang
pixel-art-scaling/shaders/edgeNpixels.slang

Ported to .slang from glsl-shaders (https://github.com/libretro/glsl-shaders/pull/490).

Add edgeNpixels shader

---

presets/crt-royale-fast/4k/crt-royale-fast-ntsc-rf-slotmask-nes.slangp
presets/crt-royale-fast/crt-royale-fast-ntsc-rf-slotmask-nes.slangp

- crt-royale-fast-ntsc-rf-slotmask-nes.slangp presets added.

Add RF-nes presets to crt-royale-fast folder

---

README.md

see: https://github.com/kokoko3k/RetroArch/commit/e1b2e29d51c1ea9a4f5ba6a726ebdc7be45e662b

Document #pragma include_optional

---

crt/shaders/crt-nobody.slang

- Better non-integer scaling;
- Improvements to brightness control;
- Add beam thickness controls;
- Add geom curvature code.

Update crt-nobody shader

---

bezel/uborder/shaders/content_shaders/crt-nobody.slang

- Add rotate option for TATE games.
- Only works if 'core option' Vertical Aspect is ON.

Update crt-nobody for uborder

---

include/img/curvature.h
include/img/hyllian_warp.h

-Add hyllian_warp.h and update curvature.h.

Add new curvature code to 'include/img'

---

border/shaders/average_fill/compose.slang
border/shaders/blur_fill/compose.slang
pixel-art-scaling/pixel_aa.slangp
pixel-art-scaling/pixel_aa_fast.slangp
pixel-art-scaling/pixel_aa_no_gamma_correction.slangp
pixel-art-scaling/pixel_aa_xform.slangp
pixel-art-scaling/shaders/pixel_aa/parameters.inc
pixel-art-scaling/shaders/pixel_aa/pixel_aa.slang
pixel-art-scaling/shaders/pixel_aa/pixel_aa_fast.slang
pixel-art-scaling/shaders/pixel_aa/pixel_aa_no_gamma_correction.slang
pixel-art-scaling/shaders/pixel_aa/pixel_aa_xform.slang
pixel-art-scaling/shaders/pixel_aa/shared.inc
pixel-art-scaling/shaders/pixel_aa/to_lin.slang
pixel-art-scaling/shaders/pixel_aa/to_lin_fast.slang

Upstreams changes from here: https://github.com/libretro/glsl-shaders/pull/502
Formatting changes are due to changing the line limit from 80 to 100 characters.

Pixel AA v1.7

---

handheld/shaders/authentic_gbc/authentic_gbc.slang
handheld/shaders/authentic_gbc/parameters.inc
handheld/shaders/lcd1x.slang
handheld/shaders/lcd1x_nds.slang
handheld/shaders/lcd1x_psp.slang
handheld/shaders/lcd3x.slang

This makes these presets work better when combining presets with append / prepend.

Update lcd*x and authentic_gbc to use OriginalSize

---

handheld/shaders/dot.slang

Same changes as in https://github.com/libretro/glsl-shaders/pull/505

Fix Dot shader

---

pixel-art-scaling/shaders/sharp-shimmerless.slang
pixel-art-scaling/sharp-shimmerless.slangp

- Sharp-shimmerless shaders from zadpos;
- Some vector optimzations done.

Add sharp-shimmerless shaders

---

bezel/uborder/base_presets/uborder-bezel-reflections/uborder-bezel-reflections-crt-nobody.slangp
bezel/uborder/shaders/content_bezel_shaders/crt-nobody-bezel-reflections.slang
bezel/uborder/shaders/content_bezel_shaders/include/uborder_bezel_reflections_common.inc

- Update integer scaling;
- Fix some bugs.

Update Uborder to v0.0.7b

---

crt/shaders/hyllian/support/glow/blur-glow-mask-geom.slang

I noticed that the mask color fix Hyllian gave me last fall has not been done.
https://discord.com/channels/184109094070779904/662208336984277012/1288457438000971818

fix mask color

---

bezel/koko-aio/config/config-user-optional-template.txt
bezel/koko-aio/config/config-user.txt
bezel/koko-aio/docs-ng.md
bezel/koko-aio/shaders-ng/config.inc
bezel/koko-aio/shaders-ng/final_pass.slang
bezel/koko-aio/shaders-ng/fxaa.slang
bezel/koko-aio/shaders-ng/halo.slang
bezel/koko-aio/shaders-ng/halo_pre_gamma.slang
bezel/koko-aio/shaders-ng/helper_pass.slang
bezel/koko-aio/shaders-ng/in_glow_x.slang
bezel/koko-aio/shaders-ng/in_glow_y.slang
bezel/koko-aio/shaders-ng/reflection_blur.slang
bezel/koko-aio/shaders-ng/reflection_blur_pre.slang
bezel/koko-aio/shaders-ng/shift_and_bleed.slang

The usual post-release "same-day" bugreport fixed...

Sync to koko-aio 1.9.63-HotFix1

---

pixel-art-scaling/shaders/soft-pixel-art.slang
pixel-art-scaling/soft-pixel-art.slangp

- A modified xSoft shader for pixel art style.

Add soft-pixel-art shaders

---

stereoscopic-3d/anaglyph-to-interlaced.slangp
stereoscopic-3d/shaders/anaglyph-to-interlaced.slang
stereoscopic-3d/shaders/sbs-to-interlaced.slang
stereoscopic-3d/side-by-side-to-interlaced.slangp

and revisit some things on the side-by-side to interlaced shader.

add anaglyph to interlaced shader

---

edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass0.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass1.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-fast-pass2.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-pass0.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-pass1.slang
edge-smoothing/xbr/shaders/super-xbr/super-xbr-pass2.slang
edge-smoothing/xbr/shaders/support/deblur-fast.slang
edge-smoothing/xbr/shaders/support/luma.slang
edge-smoothing/xbr/super-xbr-fast.slangp
edge-smoothing/xbr/super-xbr.slangp

- Now they're much sharper;
- Figured out how to deblur without adding artifacts.

Major update to Super-xBR shaders

---

misc/shaders/bob-deinterlacing.slang

Correcting a fix that was done for #255.
The values were swapped and I didn't notice until now.

Fix bob deinterlacing

---

edge-smoothing/xbr/hybrid-jinc2-xbr-lv2.slangp
edge-smoothing/xbr/shaders/support/deblur-fast.slang

- Fix some inverted gradients when using deblur-fast. Results now are cleaner.
- Update some super-xbr and hybrid presets that use new deblur-fast.

Update deblur-fast and presets

---

crt/shaders/crt-yah/common/frame-helper.h
crt/shaders/crt-yah/common/screen-helper.h
crt/shaders/crt-yah/crt-yah.fs.h
crt/shaders/crt-yah/parameters.h
crt/shaders/crt-yah/parameters.single-pass.h

This PR allows for smaller step width of the screen scale parameter. This change also reviled an issue with the scanlines offset that has been fixed. The coordinate handling has been extracted to its own functions.

CRT-Yah: correct screen scale
